app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app_rest_concert:
    resource: "@AppBundle/Controller/Api/ConcertController.php"
    type: rest
    prefix: /api